/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AuthenticatedProxyInterface extends ethers.utils.Interface {
  functions: {
    "proxy(address,uint8,bytes)": FunctionFragment;
    "proxyAssert(address,uint8,bytes)": FunctionFragment;
    "proxyType()": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "setRevoke(bool)": FunctionFragment;
    "user()": FunctionFragment;
    "implementation()": FunctionFragment;
    "revoked()": FunctionFragment;
    "upgradeabilityOwner()": FunctionFragment;
    "registry()": FunctionFragment;
    "receiveApproval(address,uint256,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "proxy",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxyAssert",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "proxyType", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "setRevoke", values: [boolean]): string;
  encodeFunctionData(functionFragment: "user", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "revoked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeabilityOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveApproval",
    values: [string, BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "proxy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxyAssert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proxyType", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRevoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "user", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeabilityOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveApproval",
    data: BytesLike
  ): Result;

  events: {
    "Revoked(bool)": EventFragment;
    "ReceivedEther(address,uint256)": EventFragment;
    "ReceivedTokens(address,uint256,address,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Revoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedEther"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedTokens"): EventFragment;
}

export type RevokedEvent = TypedEvent<[boolean] & { revoked: boolean }>;

export type ReceivedEtherEvent = TypedEvent<
  [string, BigNumber] & { sender: string; amount: BigNumber }
>;

export type ReceivedTokensEvent = TypedEvent<
  [string, BigNumber, string, string] & {
    from: string;
    value: BigNumber;
    token: string;
    extraData: string;
  }
>;

export class AuthenticatedProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AuthenticatedProxyInterface;

  functions: {
    proxy(
      dest: string,
      howToCall: BigNumberish,
      calldata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proxyAssert(
      dest: string,
      howToCall: BigNumberish,
      calldata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proxyType(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { proxyTypeId: BigNumber }>;

    initialize(
      addrUser: string,
      addrRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRevoke(
      revoke: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    user(overrides?: CallOverrides): Promise<[string]>;

    implementation(overrides?: CallOverrides): Promise<[string]>;

    revoked(overrides?: CallOverrides): Promise<[boolean]>;

    upgradeabilityOwner(overrides?: CallOverrides): Promise<[string]>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    receiveApproval(
      from: string,
      value: BigNumberish,
      token: string,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  proxy(
    dest: string,
    howToCall: BigNumberish,
    calldata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proxyAssert(
    dest: string,
    howToCall: BigNumberish,
    calldata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proxyType(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    addrUser: string,
    addrRegistry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRevoke(
    revoke: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  user(overrides?: CallOverrides): Promise<string>;

  implementation(overrides?: CallOverrides): Promise<string>;

  revoked(overrides?: CallOverrides): Promise<boolean>;

  upgradeabilityOwner(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  receiveApproval(
    from: string,
    value: BigNumberish,
    token: string,
    extraData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    proxy(
      dest: string,
      howToCall: BigNumberish,
      calldata: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    proxyAssert(
      dest: string,
      howToCall: BigNumberish,
      calldata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    proxyType(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      addrUser: string,
      addrRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setRevoke(revoke: boolean, overrides?: CallOverrides): Promise<void>;

    user(overrides?: CallOverrides): Promise<string>;

    implementation(overrides?: CallOverrides): Promise<string>;

    revoked(overrides?: CallOverrides): Promise<boolean>;

    upgradeabilityOwner(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    receiveApproval(
      from: string,
      value: BigNumberish,
      token: string,
      extraData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Revoked(bool)"(
      revoked?: null
    ): TypedEventFilter<[boolean], { revoked: boolean }>;

    Revoked(revoked?: null): TypedEventFilter<[boolean], { revoked: boolean }>;

    "ReceivedEther(address,uint256)"(
      sender?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { sender: string; amount: BigNumber }
    >;

    ReceivedEther(
      sender?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { sender: string; amount: BigNumber }
    >;

    "ReceivedTokens(address,uint256,address,bytes)"(
      from?: string | null,
      value?: null,
      token?: string | null,
      extraData?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string],
      { from: string; value: BigNumber; token: string; extraData: string }
    >;

    ReceivedTokens(
      from?: string | null,
      value?: null,
      token?: string | null,
      extraData?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string],
      { from: string; value: BigNumber; token: string; extraData: string }
    >;
  };

  estimateGas: {
    proxy(
      dest: string,
      howToCall: BigNumberish,
      calldata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proxyAssert(
      dest: string,
      howToCall: BigNumberish,
      calldata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proxyType(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      addrUser: string,
      addrRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRevoke(
      revoke: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    user(overrides?: CallOverrides): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<BigNumber>;

    revoked(overrides?: CallOverrides): Promise<BigNumber>;

    upgradeabilityOwner(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    receiveApproval(
      from: string,
      value: BigNumberish,
      token: string,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    proxy(
      dest: string,
      howToCall: BigNumberish,
      calldata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proxyAssert(
      dest: string,
      howToCall: BigNumberish,
      calldata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proxyType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      addrUser: string,
      addrRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRevoke(
      revoke: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    user(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    implementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revoked(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    upgradeabilityOwner(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiveApproval(
      from: string,
      value: BigNumberish,
      token: string,
      extraData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
