/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface GenArt721Interface extends ethers.utils.Interface {
  functions: {
    "addProject(uint256,bool)": FunctionFragment;
    "addProjectScript(uint256,string)": FunctionFragment;
    "addWhitelisted(address)": FunctionFragment;
    "admin()": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "artblocksAddress()": FunctionFragment;
    "artblocksPercentage()": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "clearTokenIpfsImageUri(uint256)": FunctionFragment;
    "getApproved(uint256)": FunctionFragment;
    "getRoyaltyData(uint256)": FunctionFragment;
    "hashToTokenId(bytes32)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "isWhitelisted(address)": FunctionFragment;
    "name()": FunctionFragment;
    "nextProjectId()": FunctionFragment;
    "overrideTokenDynamicImageWithIpfsLink(uint256,string)": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "projectDetails(uint256)": FunctionFragment;
    "projectScriptByIndex(uint256,uint256)": FunctionFragment;
    "projectScriptInfo(uint256)": FunctionFragment;
    "projectShowAllTokens(uint256)": FunctionFragment;
    "projectTokenInfo(uint256)": FunctionFragment;
    "projectURIInfo(uint256)": FunctionFragment;
    "purchase(uint256)": FunctionFragment;
    "purchaseTo(address,uint256)": FunctionFragment;
    "removeProjectLastScript(uint256)": FunctionFragment;
    "removeWhitelisted(address)": FunctionFragment;
    "safeTransferFrom(address,address,uint256)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "showTokenHashes(uint256)": FunctionFragment;
    "staticIpfsImageLink(uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "toggleProjectIsActive(uint256)": FunctionFragment;
    "toggleProjectIsDynamic(uint256)": FunctionFragment;
    "toggleProjectIsLocked(uint256)": FunctionFragment;
    "toggleProjectIsPaused(uint256)": FunctionFragment;
    "toggleProjectUseIpfsForStatic(uint256)": FunctionFragment;
    "tokenByIndex(uint256)": FunctionFragment;
    "tokenIdToProjectId(uint256)": FunctionFragment;
    "tokenOfOwnerByIndex(address,uint256)": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "tokensOfOwner(address)": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "updateArtblocksAddress(address)": FunctionFragment;
    "updateArtblocksPercentage(uint256)": FunctionFragment;
    "updateProjectAdditionalPayeeInfo(uint256,address,uint256)": FunctionFragment;
    "updateProjectArtistAddress(uint256,address)": FunctionFragment;
    "updateProjectArtistName(uint256,string)": FunctionFragment;
    "updateProjectBaseIpfsURI(uint256,string)": FunctionFragment;
    "updateProjectBaseURI(uint256,string)": FunctionFragment;
    "updateProjectDescription(uint256,string)": FunctionFragment;
    "updateProjectHashesGenerated(uint256,uint256)": FunctionFragment;
    "updateProjectIpfsHash(uint256,string)": FunctionFragment;
    "updateProjectLicense(uint256,string)": FunctionFragment;
    "updateProjectMaxInvocations(uint256,uint256)": FunctionFragment;
    "updateProjectName(uint256,string)": FunctionFragment;
    "updateProjectPricePerTokenInWei(uint256,uint256)": FunctionFragment;
    "updateProjectScript(uint256,uint256,string)": FunctionFragment;
    "updateProjectScriptJSON(uint256,string)": FunctionFragment;
    "updateProjectSecondaryMarketRoyaltyPercentage(uint256,uint256)": FunctionFragment;
    "updateProjectWebsite(uint256,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addProject",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "addProjectScript",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addWhitelisted",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "artblocksAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "artblocksPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "clearTokenIpfsImageUri",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoyaltyData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashToTokenId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextProjectId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "overrideTokenDynamicImageWithIpfsLink",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectScriptByIndex",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectScriptInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectShowAllTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectTokenInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectURIInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeProjectLastScript",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWhitelisted",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "showTokenHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "staticIpfsImageLink",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "toggleProjectIsActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleProjectIsDynamic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleProjectIsLocked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleProjectIsPaused",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleProjectUseIpfsForStatic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIdToProjectId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensOfOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateArtblocksAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateArtblocksPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectAdditionalPayeeInfo",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectArtistAddress",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectArtistName",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectBaseIpfsURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectBaseURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectDescription",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectHashesGenerated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectIpfsHash",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectLicense",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectMaxInvocations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectName",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectPricePerTokenInWei",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectScript",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectScriptJSON",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectSecondaryMarketRoyaltyPercentage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectWebsite",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "addProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addProjectScript",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "artblocksAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "artblocksPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clearTokenIpfsImageUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoyaltyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashToTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextProjectId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "overrideTokenDynamicImageWithIpfsLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectScriptByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectScriptInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectShowAllTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectURIInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "purchaseTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeProjectLastScript",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "showTokenHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "staticIpfsImageLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleProjectIsActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleProjectIsDynamic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleProjectIsLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleProjectIsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleProjectUseIpfsForStatic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIdToProjectId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokensOfOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateArtblocksAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateArtblocksPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectAdditionalPayeeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectArtistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectArtistName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectBaseIpfsURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectBaseURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectHashesGenerated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectIpfsHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectMaxInvocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectPricePerTokenInWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectScript",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectScriptJSON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectSecondaryMarketRoyaltyPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectWebsite",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "Mint(address,uint256,uint256,uint256,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Mint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber] & {
    owner: string;
    approved: string;
    tokenId: BigNumber;
  }
>;

export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean] & {
    owner: string;
    operator: string;
    approved: boolean;
  }
>;

export type MintEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
    _to: string;
    _tokenId: BigNumber;
    _projectId: BigNumber;
    _invocations: BigNumber;
    _value: BigNumber;
  }
>;

export type TransferEvent = TypedEvent<
  [string, string, BigNumber] & { from: string; to: string; tokenId: BigNumber }
>;

export class GenArt721 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GenArt721Interface;

  functions: {
    addProject(
      _pricePerTokenInWei: BigNumberish,
      _dynamic: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addProjectScript(
      _projectId: BigNumberish,
      _script: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addWhitelisted(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    artblocksAddress(overrides?: CallOverrides): Promise<[string]>;

    artblocksPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    clearTokenIpfsImageUri(
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoyaltyData(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber] & {
        artistAddress: string;
        additionalPayee: string;
        additionalPayeePercentage: BigNumber;
        royaltyFeeByID: BigNumber;
      }
    >;

    hashToTokenId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWhitelisted(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    nextProjectId(overrides?: CallOverrides): Promise<[BigNumber]>;

    overrideTokenDynamicImageWithIpfsLink(
      _tokenId: BigNumberish,
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    projectDetails(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, boolean] & {
        projectName: string;
        artist: string;
        description: string;
        website: string;
        license: string;
        dynamic: boolean;
      }
    >;

    projectScriptByIndex(
      _projectId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    projectScriptInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, boolean, boolean] & {
        scriptJSON: string;
        scriptCount: BigNumber;
        hashes: BigNumber;
        ipfsHash: string;
        locked: boolean;
        paused: boolean;
      }
    >;

    projectShowAllTokens(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    projectTokenInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, boolean, string, BigNumber] & {
        artistAddress: string;
        pricePerTokenInWei: BigNumber;
        invocations: BigNumber;
        maxInvocations: BigNumber;
        active: boolean;
        additionalPayee: string;
        additionalPayeePercentage: BigNumber;
      }
    >;

    projectURIInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & {
        projectBaseURI: string;
        projectBaseIpfsURI: string;
        useIpfs: boolean;
      }
    >;

    purchase(
      _projectId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    purchaseTo(
      _to: string,
      _projectId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeProjectLastScript(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeWhitelisted(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      to: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    showTokenHashes(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    staticIpfsImageLink(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    toggleProjectIsActive(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleProjectIsDynamic(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleProjectIsLocked(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleProjectIsPaused(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleProjectUseIpfsForStatic(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenIdToProjectId(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenURI(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    tokensOfOwner(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateArtblocksAddress(
      _artblocksAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateArtblocksPercentage(
      _artblocksPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectAdditionalPayeeInfo(
      _projectId: BigNumberish,
      _additionalPayee: string,
      _additionalPayeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectArtistAddress(
      _projectId: BigNumberish,
      _artistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectArtistName(
      _projectId: BigNumberish,
      _projectArtistName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectBaseIpfsURI(
      _projectId: BigNumberish,
      _projectBaseIpfsURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectBaseURI(
      _projectId: BigNumberish,
      _newBaseURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectDescription(
      _projectId: BigNumberish,
      _projectDescription: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectHashesGenerated(
      _projectId: BigNumberish,
      _hashes: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectIpfsHash(
      _projectId: BigNumberish,
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectLicense(
      _projectId: BigNumberish,
      _projectLicense: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectMaxInvocations(
      _projectId: BigNumberish,
      _maxInvocations: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectName(
      _projectId: BigNumberish,
      _projectName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectPricePerTokenInWei(
      _projectId: BigNumberish,
      _pricePerTokenInWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectScript(
      _projectId: BigNumberish,
      _scriptId: BigNumberish,
      _script: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectScriptJSON(
      _projectId: BigNumberish,
      _projectScriptJSON: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectSecondaryMarketRoyaltyPercentage(
      _projectId: BigNumberish,
      _secondMarketRoyalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProjectWebsite(
      _projectId: BigNumberish,
      _projectWebsite: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addProject(
    _pricePerTokenInWei: BigNumberish,
    _dynamic: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addProjectScript(
    _projectId: BigNumberish,
    _script: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addWhitelisted(
    _address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  admin(overrides?: CallOverrides): Promise<string>;

  approve(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  artblocksAddress(overrides?: CallOverrides): Promise<string>;

  artblocksPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  clearTokenIpfsImageUri(
    _tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getApproved(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoyaltyData(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber] & {
      artistAddress: string;
      additionalPayee: string;
      additionalPayeePercentage: BigNumber;
      royaltyFeeByID: BigNumber;
    }
  >;

  hashToTokenId(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  isApprovedForAll(
    owner: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isWhitelisted(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  name(overrides?: CallOverrides): Promise<string>;

  nextProjectId(overrides?: CallOverrides): Promise<BigNumber>;

  overrideTokenDynamicImageWithIpfsLink(
    _tokenId: BigNumberish,
    _ipfsHash: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  projectDetails(
    _projectId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string, boolean] & {
      projectName: string;
      artist: string;
      description: string;
      website: string;
      license: string;
      dynamic: boolean;
    }
  >;

  projectScriptByIndex(
    _projectId: BigNumberish,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  projectScriptInfo(
    _projectId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, string, boolean, boolean] & {
      scriptJSON: string;
      scriptCount: BigNumber;
      hashes: BigNumber;
      ipfsHash: string;
      locked: boolean;
      paused: boolean;
    }
  >;

  projectShowAllTokens(
    _projectId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  projectTokenInfo(
    _projectId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, boolean, string, BigNumber] & {
      artistAddress: string;
      pricePerTokenInWei: BigNumber;
      invocations: BigNumber;
      maxInvocations: BigNumber;
      active: boolean;
      additionalPayee: string;
      additionalPayeePercentage: BigNumber;
    }
  >;

  projectURIInfo(
    _projectId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, boolean] & {
      projectBaseURI: string;
      projectBaseIpfsURI: string;
      useIpfs: boolean;
    }
  >;

  purchase(
    _projectId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  purchaseTo(
    _to: string,
    _projectId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeProjectLastScript(
    _projectId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeWhitelisted(
    _address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256,bytes)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    to: string,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  showTokenHashes(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  staticIpfsImageLink(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  toggleProjectIsActive(
    _projectId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleProjectIsDynamic(
    _projectId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleProjectIsLocked(
    _projectId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleProjectIsPaused(
    _projectId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleProjectUseIpfsForStatic(
    _projectId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenByIndex(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenIdToProjectId(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenOfOwnerByIndex(
    owner: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenURI(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  tokensOfOwner(owner: string, overrides?: CallOverrides): Promise<BigNumber[]>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  transferFrom(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateArtblocksAddress(
    _artblocksAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateArtblocksPercentage(
    _artblocksPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectAdditionalPayeeInfo(
    _projectId: BigNumberish,
    _additionalPayee: string,
    _additionalPayeePercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectArtistAddress(
    _projectId: BigNumberish,
    _artistAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectArtistName(
    _projectId: BigNumberish,
    _projectArtistName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectBaseIpfsURI(
    _projectId: BigNumberish,
    _projectBaseIpfsURI: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectBaseURI(
    _projectId: BigNumberish,
    _newBaseURI: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectDescription(
    _projectId: BigNumberish,
    _projectDescription: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectHashesGenerated(
    _projectId: BigNumberish,
    _hashes: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectIpfsHash(
    _projectId: BigNumberish,
    _ipfsHash: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectLicense(
    _projectId: BigNumberish,
    _projectLicense: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectMaxInvocations(
    _projectId: BigNumberish,
    _maxInvocations: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectName(
    _projectId: BigNumberish,
    _projectName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectPricePerTokenInWei(
    _projectId: BigNumberish,
    _pricePerTokenInWei: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectScript(
    _projectId: BigNumberish,
    _scriptId: BigNumberish,
    _script: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectScriptJSON(
    _projectId: BigNumberish,
    _projectScriptJSON: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectSecondaryMarketRoyaltyPercentage(
    _projectId: BigNumberish,
    _secondMarketRoyalty: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProjectWebsite(
    _projectId: BigNumberish,
    _projectWebsite: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addProject(
      _pricePerTokenInWei: BigNumberish,
      _dynamic: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    addProjectScript(
      _projectId: BigNumberish,
      _script: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addWhitelisted(_address: string, overrides?: CallOverrides): Promise<void>;

    admin(overrides?: CallOverrides): Promise<string>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    artblocksAddress(overrides?: CallOverrides): Promise<string>;

    artblocksPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    clearTokenIpfsImageUri(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoyaltyData(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber] & {
        artistAddress: string;
        additionalPayee: string;
        additionalPayeePercentage: BigNumber;
        royaltyFeeByID: BigNumber;
      }
    >;

    hashToTokenId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isWhitelisted(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    nextProjectId(overrides?: CallOverrides): Promise<BigNumber>;

    overrideTokenDynamicImageWithIpfsLink(
      _tokenId: BigNumberish,
      _ipfsHash: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    projectDetails(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, boolean] & {
        projectName: string;
        artist: string;
        description: string;
        website: string;
        license: string;
        dynamic: boolean;
      }
    >;

    projectScriptByIndex(
      _projectId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    projectScriptInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, boolean, boolean] & {
        scriptJSON: string;
        scriptCount: BigNumber;
        hashes: BigNumber;
        ipfsHash: string;
        locked: boolean;
        paused: boolean;
      }
    >;

    projectShowAllTokens(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    projectTokenInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, boolean, string, BigNumber] & {
        artistAddress: string;
        pricePerTokenInWei: BigNumber;
        invocations: BigNumber;
        maxInvocations: BigNumber;
        active: boolean;
        additionalPayee: string;
        additionalPayeePercentage: BigNumber;
      }
    >;

    projectURIInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & {
        projectBaseURI: string;
        projectBaseIpfsURI: string;
        useIpfs: boolean;
      }
    >;

    purchase(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    purchaseTo(
      _to: string,
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeProjectLastScript(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    removeWhitelisted(
      _address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      to: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    showTokenHashes(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    staticIpfsImageLink(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    toggleProjectIsActive(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    toggleProjectIsDynamic(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    toggleProjectIsLocked(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    toggleProjectIsPaused(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    toggleProjectUseIpfsForStatic(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenIdToProjectId(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    tokensOfOwner(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateArtblocksAddress(
      _artblocksAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateArtblocksPercentage(
      _artblocksPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectAdditionalPayeeInfo(
      _projectId: BigNumberish,
      _additionalPayee: string,
      _additionalPayeePercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectArtistAddress(
      _projectId: BigNumberish,
      _artistAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectArtistName(
      _projectId: BigNumberish,
      _projectArtistName: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectBaseIpfsURI(
      _projectId: BigNumberish,
      _projectBaseIpfsURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectBaseURI(
      _projectId: BigNumberish,
      _newBaseURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectDescription(
      _projectId: BigNumberish,
      _projectDescription: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectHashesGenerated(
      _projectId: BigNumberish,
      _hashes: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectIpfsHash(
      _projectId: BigNumberish,
      _ipfsHash: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectLicense(
      _projectId: BigNumberish,
      _projectLicense: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectMaxInvocations(
      _projectId: BigNumberish,
      _maxInvocations: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectName(
      _projectId: BigNumberish,
      _projectName: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectPricePerTokenInWei(
      _projectId: BigNumberish,
      _pricePerTokenInWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectScript(
      _projectId: BigNumberish,
      _scriptId: BigNumberish,
      _script: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectScriptJSON(
      _projectId: BigNumberish,
      _projectScriptJSON: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectSecondaryMarketRoyaltyPercentage(
      _projectId: BigNumberish,
      _secondMarketRoyalty: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProjectWebsite(
      _projectId: BigNumberish,
      _projectWebsite: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: string | null,
      approved?: string | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; approved: string; tokenId: BigNumber }
    >;

    Approval(
      owner?: string | null,
      approved?: string | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; approved: string; tokenId: BigNumber }
    >;

    "ApprovalForAll(address,address,bool)"(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): TypedEventFilter<
      [string, string, boolean],
      { owner: string; operator: string; approved: boolean }
    >;

    ApprovalForAll(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): TypedEventFilter<
      [string, string, boolean],
      { owner: string; operator: string; approved: boolean }
    >;

    "Mint(address,uint256,uint256,uint256,uint256)"(
      _to?: string | null,
      _tokenId?: BigNumberish | null,
      _projectId?: BigNumberish | null,
      _invocations?: null,
      _value?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        _to: string;
        _tokenId: BigNumber;
        _projectId: BigNumber;
        _invocations: BigNumber;
        _value: BigNumber;
      }
    >;

    Mint(
      _to?: string | null,
      _tokenId?: BigNumberish | null,
      _projectId?: BigNumberish | null,
      _invocations?: null,
      _value?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        _to: string;
        _tokenId: BigNumber;
        _projectId: BigNumber;
        _invocations: BigNumber;
        _value: BigNumber;
      }
    >;

    "Transfer(address,address,uint256)"(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; tokenId: BigNumber }
    >;

    Transfer(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; tokenId: BigNumber }
    >;
  };

  estimateGas: {
    addProject(
      _pricePerTokenInWei: BigNumberish,
      _dynamic: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addProjectScript(
      _projectId: BigNumberish,
      _script: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addWhitelisted(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    artblocksAddress(overrides?: CallOverrides): Promise<BigNumber>;

    artblocksPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    clearTokenIpfsImageUri(
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoyaltyData(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashToTokenId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWhitelisted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    nextProjectId(overrides?: CallOverrides): Promise<BigNumber>;

    overrideTokenDynamicImageWithIpfsLink(
      _tokenId: BigNumberish,
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectDetails(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectScriptByIndex(
      _projectId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectScriptInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectShowAllTokens(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectTokenInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projectURIInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    purchase(
      _projectId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    purchaseTo(
      _to: string,
      _projectId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeProjectLastScript(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeWhitelisted(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setApprovalForAll(
      to: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    showTokenHashes(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    staticIpfsImageLink(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    toggleProjectIsActive(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleProjectIsDynamic(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleProjectIsLocked(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleProjectIsPaused(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleProjectUseIpfsForStatic(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenIdToProjectId(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokensOfOwner(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateArtblocksAddress(
      _artblocksAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateArtblocksPercentage(
      _artblocksPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectAdditionalPayeeInfo(
      _projectId: BigNumberish,
      _additionalPayee: string,
      _additionalPayeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectArtistAddress(
      _projectId: BigNumberish,
      _artistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectArtistName(
      _projectId: BigNumberish,
      _projectArtistName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectBaseIpfsURI(
      _projectId: BigNumberish,
      _projectBaseIpfsURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectBaseURI(
      _projectId: BigNumberish,
      _newBaseURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectDescription(
      _projectId: BigNumberish,
      _projectDescription: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectHashesGenerated(
      _projectId: BigNumberish,
      _hashes: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectIpfsHash(
      _projectId: BigNumberish,
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectLicense(
      _projectId: BigNumberish,
      _projectLicense: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectMaxInvocations(
      _projectId: BigNumberish,
      _maxInvocations: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectName(
      _projectId: BigNumberish,
      _projectName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectPricePerTokenInWei(
      _projectId: BigNumberish,
      _pricePerTokenInWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectScript(
      _projectId: BigNumberish,
      _scriptId: BigNumberish,
      _script: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectScriptJSON(
      _projectId: BigNumberish,
      _projectScriptJSON: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectSecondaryMarketRoyaltyPercentage(
      _projectId: BigNumberish,
      _secondMarketRoyalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProjectWebsite(
      _projectId: BigNumberish,
      _projectWebsite: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addProject(
      _pricePerTokenInWei: BigNumberish,
      _dynamic: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addProjectScript(
      _projectId: BigNumberish,
      _script: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addWhitelisted(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    artblocksAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    artblocksPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    clearTokenIpfsImageUri(
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoyaltyData(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashToTokenId(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhitelisted(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nextProjectId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    overrideTokenDynamicImageWithIpfsLink(
      _tokenId: BigNumberish,
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectDetails(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectScriptByIndex(
      _projectId: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectScriptInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectShowAllTokens(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectTokenInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectURIInfo(
      _projectId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    purchase(
      _projectId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    purchaseTo(
      _to: string,
      _projectId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeProjectLastScript(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeWhitelisted(
      _address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      to: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    showTokenHashes(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    staticIpfsImageLink(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    toggleProjectIsActive(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleProjectIsDynamic(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleProjectIsLocked(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleProjectIsPaused(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleProjectUseIpfsForStatic(
      _projectId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenIdToProjectId(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenURI(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokensOfOwner(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateArtblocksAddress(
      _artblocksAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateArtblocksPercentage(
      _artblocksPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectAdditionalPayeeInfo(
      _projectId: BigNumberish,
      _additionalPayee: string,
      _additionalPayeePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectArtistAddress(
      _projectId: BigNumberish,
      _artistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectArtistName(
      _projectId: BigNumberish,
      _projectArtistName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectBaseIpfsURI(
      _projectId: BigNumberish,
      _projectBaseIpfsURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectBaseURI(
      _projectId: BigNumberish,
      _newBaseURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectDescription(
      _projectId: BigNumberish,
      _projectDescription: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectHashesGenerated(
      _projectId: BigNumberish,
      _hashes: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectIpfsHash(
      _projectId: BigNumberish,
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectLicense(
      _projectId: BigNumberish,
      _projectLicense: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectMaxInvocations(
      _projectId: BigNumberish,
      _maxInvocations: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectName(
      _projectId: BigNumberish,
      _projectName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectPricePerTokenInWei(
      _projectId: BigNumberish,
      _pricePerTokenInWei: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectScript(
      _projectId: BigNumberish,
      _scriptId: BigNumberish,
      _script: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectScriptJSON(
      _projectId: BigNumberish,
      _projectScriptJSON: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectSecondaryMarketRoyaltyPercentage(
      _projectId: BigNumberish,
      _secondMarketRoyalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProjectWebsite(
      _projectId: BigNumberish,
      _projectWebsite: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
